### ISSUE TITLE
Bug: suicidal behaviour not prevented

### ISSUE THREAD

**Issue by eug-vs** [asketonim/snake-game#2]
If your snack is big enough (`size >= 3`) you can try moving backwards (opposite of your movement direction) and kill yourself this way. If I wanted to die, I'd prefer other ways... Please fix this so my snack can get bigger and I don't accidentally kill it any more.

**Comment by asketonim** [comment]
Yeah, I was just about to fix it. Thanks for the feedback!
It's kinda hard to prevent suicidal behavior... :man_with_turban:
